config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  get 'fee_reminder/index'
  post 'fee_reminder/index'
  get 'send', to: 'fee_reminder#send_message'
  post 'send', to: 'fee_reminder#send_message'
  
  resources :students do
    collection { post :import}
    
    collection do
      get 'pending_fee'
      post 'pending_fee', to: 'students#send_fee_reminder', as: 'send_fee_reminder_path'
      get 'missing'
      get 'removed'
    end

    member do
      patch :undiscard      
    end
    resources :invoices
  end
 
  

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  #/student/:id/update_

  
  get 'invoices/print/:id', to: 'invoices#print', as: 'invoices_print'


  #get 'invoices#cheque', to: 'invoices#cheque', as: 'invoice_cheque'

  #get 'students#missing', to: 'students#missing', as: 'students_missing'


  get 'invoices/show/:id', to: 'students#show_invoices', as: 'students_show_invoices'

  resources :invoices do
      collection do
        match 'search' => 'invoices#search', via: [:get, :post], as: :search

        get 'cheque'

      end

      resources :particulars, except: [:show], controller: 'invoices/particulars'
  end

  namespace :admin do
    resources :dashboard
  end

  root 'invoices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/fee_reminder_controller.rb
class FeeReminderController < ApplicationController
  before_action :check_admin, only: [ :index, :send_message]

  def index
    # @sms_statuses = Student.distinct.pluck(:sms_status)
    @sms_statuses = ["error", "sent"]    
    if params[:start_date].present? && params[:end_date].present? && request.post?
      start_date = params[:start_date].to_date.beginning_of_day
      end_date = params[:end_date].to_date.end_of_day
      @students = Student.where(sent_at: start_date .. end_date).order(sent_at: :desc)
    else
      @students = Student.where(sent_at: Time.zone.today.beginning_of_day .. Time.zone.now).order(sent_at: :desc)
    end
  end

  def send_message
    if params[:message].present?
      Student.kept.first(3).each do |student|          
        begin
          BroadcastMessagesJob.perform_at(2.minutes.from_now, student, params[:message]) 
          StudentMailerJob.perform_at(3.minutes.from_now, student, params[:message])           
        rescue => e
          puts e.message          
        end
      end
      redirect_to fee_reminder_index_path, notice: 'Started sending messages to all students.'
    end
  end

  private

  def check_admin
    if !current_user.admin?
      redirect_to root_path
      flash[:error] = "Unauthorized access!"
    end
  end

end

app/helpers/fee_reminder_helper.rb
module FeeReminderHelper
end

app/views/fee_reminder/index.html.erb
<div class="container">
    <div class="text-center">        
        <%= form_tag send_path, class: 'row align-items-center mb-3', method: :post do %>
            <div class="mx-auto">
                <%= label_tag :message, 'Message', class: 'fw-bolder mb-2' %>    
                <%= text_area_tag :message, params[:message], placeholder: "Type your message to send to all Student's", class: 'form-control' %>
            
                <%= submit_tag 'Send SMS and Email', class: 'btn btn-primary my-3 col-3', data: { disable_with: "Sending message to all students..."} %>                
            </div>
        <% end %>
        <%= form_tag fee_reminder_index_path, id: 'fee-reminder-form', class: 'row g-3 align-items-end mb-3', method: :post do %>                
                <div class="col-auto">
                    <%= label_tag :fee_sent_start_date, 'Start Date' %>            
                    <%= date_field_tag :start_date, params[:start_date], max: Time.zone.today, class: 'form-control' %>
                </div>
                <div class="col-auto">
                    <%= label_tag :fee_sent_end_date, 'End Date' %>	              
                    <%= date_field_tag :end_date, params[:end_date], max: Time.zone.today, class: 'form-control' %>
                </div>                
                <div class="col-auto">
                    <%= submit_tag 'Filter', class: 'btn btn-primary' %>
                </div>
                <div class="col-auto">
                    <h6><span class="blockquote-footer">Default will be today's data</span></h6>	                    
                </div>
        <% end %>
    </div>
</div>

<div class="container d-flex align-items-start">
    <ul class="nav flex-column nav-pills me-4">
        <% @sms_statuses.each do |sms_status| %>
            <li class="nav-item">
            <%= link_to sms_status.capitalize, "#tab_#{sms_status}", class: "nav-link mb-2", data: { toggle: "tab" } %>
            </li>
        <% end %>
    </ul>

    <div class="tab-content" >
            <% @sms_statuses.each do |sms_status| %>
            <div class="tab-pane fade" id="tab_<%= sms_status %>">
                <div class="table-responsive">
                <table class="table table-sty table-hover table-striped table-bordered" width="100%">
                    <thead>
                    <tr>
                        <th>First name</th>
                        <th>Last name</th>        
                        <th>Phone number</th>
                        <th>Class</th>
                        <th>Section</th>                        
                        <th>Sms status</th>
                        <th>Sms sent_at</th>
                        <th>Message</th>        
                    </tr>
                    </thead>

                    <tbody>
                    <% @students.where(sms_status: sms_status).each do |student| %>
                        <tr>
                        <td><%= student.first_name %></td>
                        <td><%= student.last_name %></td>          
                        <td><%= student.phone_number %></td>
                        <td><%= student.grade %></td>
                        <td><%= student.section %></td>                                  
                        <td><%= student.sms_status %></td>          
                        <td><%= student.sent_at.strftime("%d-%m-%Y"+" "+"%I:%M%p") if student.sent_at.present? %></td>          
                        <td><%= student.message %></td>          
                        </tr>
                    <% end %>
                    </tbody>
                </table>
                </div>              
            </div>
            <% end %>
    </div>
</div>