config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  get 'fee_reminder/index'
  post 'fee_reminder/index'
  get 'send', to: 'fee_reminder#send_message'
  post 'send', to: 'fee_reminder#send_message'
  
  resources :students do
    collection { post :import}
    
    collection do
      get 'pending_fee'
      post 'pending_fee', to: 'students#send_fee_reminder', as: 'send_fee_reminder_path'
      get 'missing'
      get 'removed'
    end

    member do
      patch :undiscard      
    end
    resources :invoices
  end
 
  

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  #/student/:id/update_

  
  get 'invoices/print/:id', to: 'invoices#print', as: 'invoices_print'


  #get 'invoices#cheque', to: 'invoices#cheque', as: 'invoice_cheque'

  #get 'students#missing', to: 'students#missing', as: 'students_missing'


  get 'invoices/show/:id', to: 'students#show_invoices', as: 'students_show_invoices'

  resources :invoices do
      collection do
        match 'search' => 'invoices#search', via: [:get, :post], as: :search

        get 'cheque'

      end

      resources :particulars, except: [:show], controller: 'invoices/particulars'
  end

  namespace :admin do
    resources :dashboard
  end

  root 'invoices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	include Discard::Model
	
	belongs_to :student
	belongs_to :user
	has_many :particulars, dependent: :destroy
	has_paper_trail

	validates :student, presence: true
	validates :month_to, presence: true
	validates :month_from, presence: true
	validates :payment_mode, presence: true
	validates :bank_account, presence: true, if: :payment_mode_cheque?
	validates :cheque_no, presence: true, if: :payment_mode_cheque?

	validate :check_invoice_dates, on: [ :create ]
	
	after_validation :invoice_month_validity, on: [ :create, :update ]
	after_create :change_status
	after_save :update_pending_months
	after_create :send_invoice_sms
	#after_validation :repeated_invoice_month_check, on: [ :create, :update ]
	
	enum status: { paid: 0, pending: 1 }

	paginates_per 10

	
	def invoice_month_validity
		year_from = self.month_from.split("-").first.to_i
		month_frm = self.month_from.split("-").second.to_i

		year_to = self.month_to.split("-").first.to_i
		to_month = self.month_to.split("-").second.to_i

		if year_from == year_to
			if month_frm > to_month
				errors.add(:base, 'Invoice from: date should be less than Invoice to: date')
			else
			end
		end
	end

	def change_status
        if self.payment_mode == 'Cash' || self.payment_mode == 'Online'
        #   self.update_attributes!(status: 'Paid')
			self.paid!
        elsif self.payment_mode == 'Cheque'
        #   self.update_attributes!(status: 'Pending')
			self.pending!
        end
  	end
	

	def check_invoice_dates		
		student = Student.find(self.student_id)
		pending_fee = student.pending_fees
		if pending_fee.present?
			from_year, from_month = self.month_from.split("-")			
			if pending_fee[from_year].present?
				if !pending_fee[from_year].include?(from_month)
					#puts pending_fee[from_year].include?(from_month).to_s+"Pending->#{pending_fee[from_year]}"+"from_month->#{from_month}"							
					errors.add(:month_from, 'Invoice exists!')
				else									
				end
				if pending_fee[from_year].include?(from_month) && pending_fee[from_year].index(from_month) != 0
					# errors.add(:base, 'There are months pending for this student before'.concat(" "+from_month.concat("-01").to_date.strftime("%B")))					
					errors.add(:base, 'There are months pending for this student before the entered month')				
				else					
				end
			end
		end		
	end


	def update_pending_months
		student = Student.find(self.student_id)        
		student.update_column(:pending_fees, InvoiceService::CalculatePendingFee.pending(student))
		InvoiceService::FeePendingStatus.update_status(student)
	end

	private

	def payment_mode_cheque?
		payment_mode == 'Cheque'
	end

	def send_invoice_sms
		# Trigger notification to student phone_number after 5 minutes to allow staff to input invoice total
		# Blocked this feature in development for testing and running
		# SendInvoiceCreatedNotificationJob.perform_at(5.minutes.from_now, self.id) 
	end
end

app/controllers/invoices/particulars_controller.rb
class Invoices::ParticularsController < ApplicationController
  before_action :set_invoice
  before_action :set_particular, except: [:new, :create]
  before_action :set_paper_trail_whodunnit
  
  # GET /particulars or /particulars.json
  def index
    @particulars = Particular.kept
  end

  # GET /particulars/1 or /particulars/1.json
  def show
  end

  # GET /particulars/new
  def new
    @particular = Particular.new
  end

  # GET /particulars/1/edit
  def edit
  end

  # POST /particulars or /particulars.json
  def create
    @particular = Particular.new(particular_params)
    @particular.invoice = @invoice

    respond_to do |format|
      if @particular.save
        format.html { redirect_to @invoice, notice: "Fee was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /particulars/1 or /particulars/1.json
  def update
    respond_to do |format|
      if @particular.update(particular_params)
        format.html { redirect_to particular_url(@particular), notice: "Fee was successfully updated." }
        format.json { render :show, status: :ok, location: @particular }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @particular.errors, status: :unprocessable_entity }
      end
    end
  end

#updated
  # DELETE /particulars/1 or /particulars/1.json
  def destroy
    @particular = Particular.find(params[:id])
    title = @particular.fee_type
    if @particular.discard
      @particular.discard
      @particular.update(discarded_by: current_user.id)
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @invoice
    else
      flash[:error] = "There was an error deleting the Fee."
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_particular
      @particular = Particular.find(params[:id])
    end

    def set_invoice
      @invoice = Invoice.find(params[:invoice_id])
    end

    # Only allow a list of trusted parameters through.
    def particular_params
      params.require(:particular).permit(:fee_type, :amount, :invoice_id, :price)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy print pdf]
  before_action :check_admin, only: :cheque
  before_action :set_paper_trail_whodunnit
  # GET /invoices or /invoices.json
  def index
    @q = Invoice.ransack(params[:q])
    @invoices = @q.result(distinct: true).order('created_at DESC').page(params[:page])    
  end

  def search
    index
    render :index
  end

  def print
    pdf
  end

  def pdf
    respond_to do |format|
      format.html
      format.pdf do
          render pdf: "Receipt for (#{@invoice.student.first_name} #{@invoice.student.last_name})",
          page_size: 'A4',
          template: 'invoices/print.html.erb',
          lowquality: true,
          dpi: 100,
          encoding: 'utf8'
        end
      end
  end


  def cheque
    @invoices = Invoice.kept.where(status: :pending)
    if @invoices.present?
      render 'cheque_data.html.erb'
    else
      flash[:alert] = "No Cheque Invoices found in Pending!"
      redirect_to root_path
    end
  end  

  # GET /invoices/1 or /invoices/1.json
  def show
    begin
      @invoice = Invoice.find(params[:id])
      @student = Student.find_by_id(@invoice.student_id)
      @particulars = @invoice.particulars
      @particular = Particular.new
    rescue StandardError => e
      redirect_to root_path
      flash[:error] = e.message
    end
  end

  # GET /invoices/new
  def new
    @student = Student.find(params[:student_id])
    @invoice = Invoice.new
    @particulars = @invoice.particulars
  end

  # GET /invoices/1/edit
  def edit
    @student = Student.find_by_id(@invoice.student_id)
    @particulars = @invoice.particulars
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    @student = @invoice.student
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
    # update_pending_months(@student)
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    if (invoice_params[:month_from] || invoice_params[:month_to]) && !current_user.admin?
      flash[:error] = 'Unauthorized to update months in invoice after creating'
      redirect_to invoice_url(@invoice)    
    else      
      respond_to do |format|
        @invoice = Invoice.find(params[:id])
        @student = @invoice.student
        if @invoice.update(invoice_params)
          format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
          format.json { render :show, status: :ok, location: @invoice }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @invoice.errors, status: :unprocessable_entity }
        end
      end
      # update_pending_months(@student)
    end    
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.discard
    @invoice.update_attributes!(discarded_by: current_user.id)
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:date, :total, :user_id, :payment_mode, :student_id, :class_no, :cheque_no, :receipt_number, :bank_account, :status, :month_from, :month_to, :discarded_by, :notes)
    end  

    def check_admin
      if !current_user.admin?
        redirect_to root_path
        flash[:error] = "Unauthorized access!"
      end
    end 
end

app/helpers/invoices_helper.rb
module InvoicesHelper

	def month_name(str)
		if str == ""
			return nil
		else
			mon_name = ["January","February","March","April","May","June","July","August","September","October","November","December"]
			mon_num = str.split("-").second.to_i
			return mon_name[mon_num-1]
		end
	end
end

app/views/invoices/_admin.html.erb
<div class="card border-dark">
        <div class="card-header text-dark">
              <%= search_form_for @q, url: search_invoices_path, html: { method: :post, class: 'container'} do |f| %>
                <div class="adm-date-field">
                  <ul class="list-inline text-center justify-content-center">

                    <li class="list-inline-item">
                     <div class="input-group" id="adm-inv-input-gp">
                         <span class="input-group-text" id="addon-wrapping">Date From:</span>
                         <b><%=f.date_field :created_at_gteq, autofocus: true, max: Time.zone.today+1.day, class: "form-control rounded-left", aria_describedby: "addon-wrapping" %></b>
                     </div>
                    </li>

                    <li class="list-inline-item">
                     <div class="input-group" id="adm-inv-input-gp">
                         <span class="input-group-text" id="addon-wrapping">Date To:</span>
                         <b><%=f.date_field :created_at_lteq, autofocus: true, max: Time.zone.today+1.day, class: "form-control rounded-left", aria_describedby: "addon-wrapping" %></b>
                     </div>
                    </li>

                    <li class="list-inline-item">
                     <div class="input-group" id="adm-inv-input-gp">
                         <span class="input-group-text" id="addon-wrapping">Invoice ID:</span>
                         <b><%=f.number_field :id_eq, autofocus: true, max: Time.zone.today+1.day, class: "form-control rounded-left", aria_describedby: "addon-wrapping", style: "width:auto;" %></b>
                     </div>
                    </li>

                    <li class="list-inline-item">
                      <div class="btn-group" role="group" id="adm-inv-btn-group">
                        <%= f.submit "Search", class: "form-control btn btn-outline-primary rounded" %>
                      
                        <%= link_to "Reset",root_path, class: "btn btn-outline-dark rounded form-control ms-2" %>

                        <%# link_to "Dashboard",admin_dashboard_index_path, class: "btn btn-outline-success rounded form-control" %>
                      </div>
                    </li>
                  </ul>
                </div>
              <% end %>
        
          </div>
        
          <div class="table-responsive">
            <table class="table invoice-sty table-hover table-sm text-center ">
              <thead>
                <tr>
                    <th><%= sort_link(@q, :id, 'Invoice ID:') %></th>
                    <th><%= sort_link(@q, :created_at, 'Created On') %></th>
                    <th>Student</th>
                    <th>Total</th>
                    <th>Paid for</th>
                    <th><%= sort_link(@q, :payment_mode, 'Payment Mode') %></th>
                    <th>Class</th>
                    <th>Created By</th>
                    <th colspan="4" class="text-center">Actions</th>
                </tr>
              </thead>

              <tbody>
                  
                  <% @invoices.each do |invoice| %>
                  <% missing_inv_month_ids = [] %>
                  <% @invoices.kept.each do |inv| %>
                      <% if !inv.month_to.present? || !inv.month_from.present? %>
                        <% missing_inv_month_ids << inv.id %>
                        <% flash[:error] = "Invoice from/to is missing for Invoice ids: #{Array.new(missing_inv_month_ids)} in this page" %>
                      <% end %>
                  <% end %>

                  
                        <tr>
                          <td><%= invoice.id %></td>
                          <td><%= invoice.created_at.strftime("%d-%m-%Y") %></td>
                          <td><%= invoice.student.first_name %> <%= invoice.student.last_name %></td>
                          <td><%= invoice.total %></td>
                          <td>
                           
                                <% if month_name(invoice.month_from) != month_name(invoice.month_to) %>
                                    <%= month_name(invoice.month_from).present? ? month_name(invoice.month_from)+" "+invoice.month_from.split("-").first[2,3] : "<a href='#''>Missing</a>".html_safe %> to <%= month_name(invoice.month_to).present? ? month_name(invoice.month_to)+" "+invoice.month_to.split("-").first[2,3] : "<a href='#''>Missing</a>".html_safe %>
                                  <% else %>
                                    <%= month_name(invoice.month_to).present? ? month_name(invoice.month_to)+" "+invoice.month_to.split("-").first[2,3] : "<a href='#''>Missing</a>".html_safe %>
                                  <% end %>
                           
                                
                           
                          </td>
                          <td><%= invoice.payment_mode %></td>
                          <td><%= invoice.student.grade %></td>
                          <td><%= invoice.user.username %></td>
                          <td><%= link_to 'Show <i class="bi bi-receipt-cutoff"></i>'.html_safe, invoice, style: 'font-size:0.9em;',class: 'btn btn-outline-primary' %></td>
                          <td><%= link_to 'Edit <i class="bi bi-pass-fill"></i>'.html_safe, edit_invoice_path(invoice), style: 'font-size:0.9em;', class: 'btn btn-outline-secondary' %></td>
                          <% if invoice.kept? %>
                                <td><%= link_to 'Delete <i class="bi bi-trash3-fill"></i>'.html_safe, invoice, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-outline-danger', style: 'font-size:0.9em;'%></td>
                          <% else %>
                                <td><strong>Already Deleted!</strong></td>
                          <% end %>
                          
                        </tr>
                      <% end %>
                </tbody>

                <!--<tfoot> add total for table for admin
                  <tr>
                    <th colspan="2"></th>
                    <th>Total: <% @invoices.where(created_at: (Time.zone.today.beginning_of_day-1.week)..Time.zone.today.end_of_day).sum(:total) %></th>
                  </tr>
                </tfoot> -->
            </table>
          </div>

        <div class="card-body text-center">
          
          <div class="btn-group">
            <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% total_of_day = Invoice.kept.where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day, status: :paid).sum(:total) + Invoice.kept.where(payment_mode: 'Cheque', status: :paid, updated_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day).sum(:total) %>
              Total for <%= Time.zone.today.strftime("%d-%m-%Y") %> : <%= number_to_currency(total_of_day, unit: "₹", raise: true) %>
            </button>
            <div class="dropdown-menu text-center" style="width:100%">
              <a class="dropdown-item" href="#">Cash : <%= number_to_currency(Invoice.kept.where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day, payment_mode: 'Cash').sum(:total), unit: "₹", raise: true) %></a>
              <a class="dropdown-item" href="#">Online : <%= number_to_currency(Invoice.kept.where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day, payment_mode: 'Online').sum(:total), unit: "₹", raise: true) %></a>
              <a class="dropdown-item" href="#">Cheque : <%= number_to_currency(Invoice.kept.where(payment_mode: 'Cheque', status: :paid, updated_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day).sum(:total), unit: "₹", raise: true) %></a>
            </div>
          </div>          

          <!--<ul class="list-inline text-center d-flex justify-content-center">
            <li class="list-group-item">
              Total Cash amount for <%# Time.zone.today.strftime("%d-%m-%Y") %> :
              <span class="total-amt rounded"> <%# number_to_currency(Invoice.all.kept.where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day, payment_mode: 'Cash').sum(:total), unit: "₹", raise: true) %></span>
            </li>
            <li class="list-group-item">
              Total Online amount for <%# Time.zone.today.strftime("%d-%m-%Y") %> :
              <span class="total-amt rounded"> <%# number_to_currency(Invoice.all.kept.where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day, payment_mode: 'Online').sum(:total),unit: "₹", raise: true) %></span>
            </li>
          </ul> -->
        </div>


        <div class="card-footer justify-content-center">          
          <%= paginate @invoices %>          
        </div>
</div>

app/views/invoices/_unauth_error.html.erb
<%= stylesheet_link_tag 'errors', media: 'all', 'data-turbolinks-track': 'reload' %>
<body>
    <div id="notfound">
        <div class="notfound">
                <div class="notfound-404">
                        <div></div>
                        <h1>404</h1>
                </div>
                <h2>Page not found</h2>
                <p class="font-monospace">The page you are looking for might have been removed or had its name changed or is temporarily unavailable.</p>
                <%= link_to 'Back <i class="bi bi-arrow-left-circle"></i>'.html_safe, root_path, class: 'btn btn-outline-dark btn-lg' %>
        </div>
    </div>
        <script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"771b8ef9a8c183f5","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2022.11.3","si":100}' crossorigin="anonymous"></script>
</body>
</html>

app/views/invoices/cheque_data.html.erb
<div class="card border-dark">
		<div class="card-header text-dark">
			<div class="table-responsive">
				<table class="table table-hover table-bordered">
					<thead>
						<tr>
							<th>Invoice id</th>
							<th>Date</th>
							<th>Student Name</th>
							<th>Status</th>
							<th>Cheque No</th>
							<th>Amount</th>
							<th>Bank Name</th>
						</tr>
					</thead>


					<tbody>
						<% @invoices.each do |invoice| %>
							<tr>
								<td><%= link_to invoice.id, invoice_path(invoice) %></td>
								<td><%= invoice.created_at.strftime("%d-%m-%Y") %></td>
								<td><%= invoice.student.first_name %> <%= invoice.student.last_name %></td>
								<td><%= invoice.status %></td>
								<td><%= invoice.cheque_no %></td>
								<td><%= invoice.total %></td>
								<td><%= invoice.bank_account.upcase if invoice.bank_account.present?  %></td>
								<!-- <td><%# button_to 'Mark as Paid', invoice, method: :put, params: {"invoice[status]" => "paid"}, class: 'btn btn-outline-success', style: 'width:250px' %></td> -->
								<td>  <%= button_to 'Mark as Paid', invoice_path(invoice, invoice: { status: 'paid' }), method: :patch, class: 'btn btn-outline-success', style: 'width:250px' %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>			
		</div>
</div>

app/views/invoices/index.html.erb
<div class="container" style="max-width: 80em;font-size:0.95em;">
      <% if current_user.admin? %>
            <%= render 'invoices/admin' %>
      <% else %>
            <%= render 'invoices/user' %>
      <% end %>
</div>

app/views/invoices/new.html.erb
<div class="container text-center" style="max-width: 35em;">
	<h3>Creating new Invoice for <u><%= @student.first_name %></u> </h3>

	<%= render 'form', invoice: @invoice %>

	<%# link_to 'Back <i class="bi bi-arrow-left-circle"></i>'.html_safe, invoices_path, class: 'btn btn-outline-dark btn-lg',style:'margin-top:1em;' %>
</div>

app/views/invoices/show.html.erb
<div class="container-xl me-0 pe-5 text-center">
    <div class="card border-dark" style="max-width: 70em;margin-top: 1.7em;">
        <div class="card-header text-dark">
            <ul class="list-inline text-center d-flex justify-content-center">  
                
                <li class="inv-list">
                    <strong>Date:</strong>
                    <%= @invoice.created_at.strftime('%d/%m/%Y') %>
                  

                 </li>

                 <li class="inv-list">
                    <strong>Student:</strong>
                    <%= link_to @invoice.student.first_name, student_path(@invoice.student) %>

                  </li>
                    
                  <li class="inv-list">
                    <strong>Class:</strong>
                    <%= @invoice.class_no %>
                  </li>

                  <li class="inv-list">
                    <strong>Payment Mode:</strong>
                    <%= @invoice.payment_mode %>
                  </li>

                  <% if @invoice.receipt_number.present? %>
                      <li class="inv-list">
                        <strong>Receipt No:</strong>
                        <%= @invoice.receipt_number %>
                      </li>
                  <% end %>

                  <li class="inv-list">
                    <strong>Total:</strong>
                    <%= @invoice.total || 0.00 %>
                  </li>

                  <li class="inv-list">
                    <strong>Submitted By:</strong>
                    <%= @invoice.user.username %>
                  </li>

                  <li class="inv-list">
                    <strong>Invoice_From:</strong>
                    <%= @invoice.month_from.present? ? month_name(@invoice.month_from)+" "+@invoice.month_from.split("-").first[2,3] : "<a href='#''>Missing</a>".html_safe %>
                  </li>

                  <li class="inv-list">
                    <strong>Invoice_To:</strong>
                    <%= @invoice.month_to.present? ? month_name(@invoice.month_to)+" "+@invoice.month_to.split("-").first[2,3] : "<a href='#''>Missing</a>".html_safe %>
                  </li>

                  <% if @invoice.payment_mode == 'Cheque' %>
                    <li class="inv-list">
                      <strong>Status:</strong>
                      <span class="badge <%= @invoice.pending? ? 'pending-status' : 'paid-status' %>"><%= @invoice.status.capitalize %><span>
                    </li>
                    
                    <li class="inv-list">
                      <strong>Cheque No:</strong>
                      <%= @invoice.cheque_no %>
                    </li>

                    <li class="inv-list">
                      <strong>Bank Name:</strong>
                      <%= @invoice.bank_account.capitalize %>
                    </li>
                  <% end %>

                  <!--Old logic code. Now cheque data is added during invoice creation. -->
                   <%# if @invoice.payment_mode == 'Cheque' && !@invoice.cheque_no.present? && !@invoice.bank_account.present? %>
                    <%# form_for @invoice do |form| %>
                    <!--<li class="inv-list">
                      <div class="form-group">
                        <div class="input-group"> -->
                            <!--<span class="input-group-text" id="addon-wrapping"><strong>Cheque No:</strong></span> -->
                            <%# form.text_field :cheque_no, autofocus: true, class: "form-control rounded-left text-center", aria_describedby: "addon-wrapping", style: 'width:auto;', placeholder: 'Enter Cheque No.' %>
                            <!--<span class="input-group-text" id="addon-wrapping"><strong>Cheque No:</strong></span> -->
                            <%# form.text_field :bank_account, autofocus: true, class: "form-control rounded-left text-center", aria_describedby: "addon-wrapping", style: 'width:auto;', placeholder: 'Enter Bank Name' %>
                        <!--</div>
                        <%# form.submit "Submit Cheque_details" ,class: 'btn btn-outline-primary rounded', style: 'width:auto;' %>
                      </div> 
                      
                    <%# end %>
                    </li> -->
                  <%# elsif @invoice.payment_mode == 'Cheque' && @invoice.cheque_no.present? && @invoice.cheque_no.present? %>
                  
                  <%# end %>

            </ul>
        </div>

            <div class="card-body">
              <div class="media">
                <div class="media-body">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>No.</th>
                        <th>Fee_type</th>
                        <th>Amount</th>
                        <th>Delete</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>
                    
                    <tbody>
                      <% cur_total = 0.00 %>
                      <% i = 0 %>
                      <% @particulars.kept.each do |particular| %>
                        <% i+=1 %>

                        <tr>
                            <td><h5><%= i %></h5></td>
                          <td><h5><%= particular.fee_type %></h5></td>
                          <td><h5><%= number_to_currency(particular.amount, unit: "₹", raise: true) %></h5></td>
                          <% if current_user.admin? || current_user.id == particular.invoice.user_id %>
                            <td><h6><%= link_to 'Delete <i class="bi bi-trash3-fill"></i>'.html_safe, [@invoice,particular], method: :delete, confirm: "Are you sure of deleting this fee?" %></h6></td>
                          
                          <% end %>

                          <% cur_total += particular.amount.to_d.round %>

                        </tr>
                        
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>


              <%= link_to 'Add new items', "#" , class: 'btn btn-outline-primary', data: { bs_toggle: 'modal', bs_target: '#modalAddPart' } %>
              

              <div class="modal fade" id="modalAddPart" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" style="font-family: open-sans;">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header bg-grey">
                      <h5 class="modal-title" id="exampleModalLabel">Add Fee for <%= @invoice.student.first_name %> </h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">                      
                      <%= render "invoices/particulars/form", { invoice: @invoice, particular: @particular }%>
                    </div>
                  </div>
                </div>
              </div>
              
              <%# link_to 'Add new items', new_invoice_particular_path(@invoice), class: 'btn btn-outline-primary' %>
              
              <h4 >Total: <%= number_to_currency(cur_total, unit: "₹", raise: true) %></h4>
              <%= button_to 'Submit Fees', @invoice, method: :patch, 
                  params: {"invoice[total]" => cur_total}, class: 'btn btn-outline-success', style: 'width:250px'
                 %>
        </div>


        <div class="card-footer text-center">
            <div class="btn-group">
                  <% if current_user.admin? || current_user.id == @invoice.user_id%>
                        <%= link_to 'Edit <i class="bi bi-pass-fill"></i>'.html_safe, edit_invoice_path(@invoice), class: 'btn btn-outline-secondary' %>
                  <% end %>
                  <% link_to 'Back <i class="bi bi-arrow-left-circle"></i>'.html_safe, root_path, class: 'btn btn-outline-dark' %>
                  <%= link_to 'Preview <i class="bi bi-file-earmark-pdf"></i>'.html_safe, invoices_print_path(@invoice) , class: 'btn btn-outline-success'%>
            </div>
        </div>
  </div>
</div>