config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  get 'fee_reminder/index'
  post 'fee_reminder/index'
  get 'send', to: 'fee_reminder#send_message'
  post 'send', to: 'fee_reminder#send_message'
  
  resources :students do
    collection { post :import}
    
    collection do
      get 'pending_fee'
      post 'pending_fee', to: 'students#send_fee_reminder', as: 'send_fee_reminder_path'
      get 'missing'
      get 'removed'
    end

    member do
      patch :undiscard      
    end
    resources :invoices
  end
 
  

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  #/student/:id/update_

  
  get 'invoices/print/:id', to: 'invoices#print', as: 'invoices_print'


  #get 'invoices#cheque', to: 'invoices#cheque', as: 'invoice_cheque'

  #get 'students#missing', to: 'students#missing', as: 'students_missing'


  get 'invoices/show/:id', to: 'students#show_invoices', as: 'students_show_invoices'

  resources :invoices do
      collection do
        match 'search' => 'invoices#search', via: [:get, :post], as: :search

        get 'cheque'

      end

      resources :particulars, except: [:show], controller: 'invoices/particulars'
  end

  namespace :admin do
    resources :dashboard
  end

  root 'invoices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
	include Discard::Model
	
	has_many :invoices, dependent: :destroy
	has_paper_trail

	paginates_per 10

	validates :first_name, presence: true
	#validates :last_name, presence: true   Some cases dont have last_name
	validates :dob, presence: true
	validates :date_of_admission, presence: true
	validates :admission_no, presence: true, uniqueness: true

	#validates :phone_number, numericality: { only_integer: true }, length: { is: 10 }
	validates :grade, presence: true
	validates :section, presence: true,  unless: Proc.new { |a| a.grade == "Playgroup" }
	validates :father_name, presence: true
	validates :mother_name, presence: true
		
	 #Removed the presense and uniqeness as some cases dont have number now + uniquesness is not needed as one parent can have multiple students
	 #Later will add presence once all have number updated
	# validates :phone_number, presence: true, numericality: { only_integer: true }, length: { is: 10 }
	# validates :email, presence: true

	validate :validate_dob

	enum sms_status: { default: 0, sent: 1, error: 2 }
	

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Student.create! row.to_hash
		end
	end

	def student_name
		if last_name.present?
		  "#{first_name} #{last_name}"
		else
		  first_name
		end
	end


	private

	def validate_dob
		if self.date_of_admission.present? && self.dob.present?
			if self.date_of_admission < self.dob
	        	errors.add(:date_of_admission,'should be a date after Date of Birth.')
	        end
	    else
	    	errors.add(:base, 'Date of admission or Date of birth is Missing')
	    end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy send_fee_reminder]
  before_action :set_paper_trail_whodunnit
  before_action :check_admin, only: %i[ removed ]
  
  # GET /students or /students.json
  def index
    @q = Student.ransack(params[:q])
    @students = @q.result(distinct: true).kept
    @students = @students.order('grade DESC').page(params[:page]) #To not let pagination affect ransack search
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  def pending_fee
    @students = Student.where(fee_pending: true).page(params[:page])
    cur_students = []
    Invoice.where(created_at: Time.zone.today.beginning_of_month.beginning_of_day..Time.zone.now).map { |i| cur_students << i.student }
    @current_month_students = Student.all - cur_students.uniq
    render 'pending_fee.html.erb'
  end

  def send_fee_reminder    
    resp = Services::FeeReminderService.send_fee_reminder_message(@student)
    if resp[:success]
      flash[:success] = "Sms Sent successfully!"
    else
      flash[:error] = "Sms sending failed! - #{resp[:error_message]}"
    end
    pending_fee
  end

  def removed
    @students = Student.discarded
    if @students.present?
      render 'discarded_students.html.erb'
    else
      flash[:error] = "No Students with TC"
      redirect_to students_path
    end
  end

  def undiscard
    @student = Student.find(params[:id])
    @student.undiscard
    flash[:notice] = "Student Restored!"
    redirect_to removed_students_path
  end

  def import
    if params[:file].present?
      begin
        student = Student.import(params[:file])
        if student.present?
          return redirect_to students_path, error: "Please upload CSV only!" unless params[:file].content_type == 'text/csv'
          redirect_to students_path, notice: "Students Uploaded Successfully"
        else
          redirect_to students_path
          flash[:error] = "Please upload a file to proceed."  
        end  
      rescue Exception => e
        redirect_to students_path
        flash[:error] = e.message  
      end  
    else
      redirect_to students_path
      flash[:error] = "Please upload a file to proceed."
    end
  end


  def missing
    @students = Student.where(admission_no: nil).or(Student.where(phone_number: nil)).or(Student.where(father_name: "")).or(Student.where(mother_name:"")).or(Student.where(dob: nil)).or(Student.where(date_of_admission: nil)).or(Student.where(grade: ""))
    if @students.present?
      render 'students/pending_data.html.erb'
    else
      flash[:alert] = "No Students with incomplete data!"
      redirect_to root_path
    end
  end

  def show_invoices
    set_student
    if current_user.admin?
      @invoices = @student.invoices
    else
      @invoices = @student.invoices.kept
    end
    
    if @invoices.any?
      render 'student_invoices.html.erb'
    else
      flash[:alert] = "No invoices for this student."
      redirect_to students_path
    end
    
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    #@student.undiscard if params.dig(:restore)
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.discard

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :admission_no, :phone_number, :grade, :section, :father_name, :mother_name, :dob, :date_of_admission, :discarded_at)
    end

    def check_admin
      if !current_user.admin?
        redirect_to root_path
        flash[:error] = "Unauthorized access!"
      end
    end
end

app/helpers/students_helper.rb
module StudentsHelper
	def month_names(month_numbers)
	  month_numbers.map { |month_number| Date::MONTHNAMES[month_number.to_i] }
	end
end

app/views/students/_search_form.html.erb
<!--<strong>Search Students with:</strong> -->
<%= search_form_for @q, class: 'form-group', id: 'stu-search-group' do |f| %>
  
	  <%= f.search_field :first_name_or_last_name_cont, placeholder: 'Name', class: 'form-control rounded text-center' %>
	  
	  <%= f.search_field :grade_eq, placeholder: 'Class', class: 'form-control rounded text-center' %>

	  <%= f.search_field :admission_no_eq, placeholder: 'Admission No', class: 'form-control rounded text-center' %>

	  	<div class="btn-group">
	    		<%= f.submit 'Search!', class: 'btn btn-sm btn-outline-success rounded mx-2' %>
	    		<%= link_to 'Reset', students_path, class: 'btn btn-sm btn-outline-dark rounded' %>
	    </div>
	
	
<% end %>

app/views/students/discarded_students.html.erb
<div class="table-responsive text-center" style="font-family: open-sans;font-size: 0.9em;">
	<table class="table table-hover table-striped table-bordered" cellspacing="0" width="100%">
		<thead>
		  <tr>
		    <th>First name</th>
		    <th>Last name</th>
		    <th>Date of Birth</th>
		    <th>Date of Admission</th>
		    <th>Admission no</th>
		    <th>Phone number</th>
		    <th>Class</th>
		    <th>Section</th>
		    <th>Father name</th>
		    <th>Mother name</th>
		    <th colspan="1"></th>
		  </tr>
		</thead>

		<tbody>
		  <% @students.each do |student| %>
		    <tr>
		      <td><%= student.first_name %></td>
		      <td><%= student.last_name %></td>
		      <td><%= student.dob.strftime("%d-%m-%Y") unless student.date_of_admission.nil? %></td>
		      <td><%= student.date_of_admission.strftime("%d-%m-%Y") unless student.date_of_admission.nil? %></td>
		      <td><%= student.admission_no %></td>
		      <td><%= student.phone_number %></td>
		      <td><%= student.grade %></td>
		      <td><%= student.section %></td>
		      <td><%= student.father_name %></td>
		      <td><%= student.mother_name %></td>
		      <td><%= link_to 'Restore', undiscard_student_path(student), 
		      		class: 'btn btn-outline-secondary btn-round btn-sm', 
		      		method: :patch %></td>
		    </tr>
		  <% end %>
		</tbody>

	</table>
	
</div>

app/views/students/edit.html.erb
<div class="container text-center" style="max-width:60em;font-family: 'open-sans';">
	<h2>Editing record for <u><%= @student.first_name.capitalize %></u></h2>

	<%= render 'form', student: @student %>
	<% if @student.kept? %>
	<div class="btn-group" role="group" style="width:400px;margin-top: 10px;margin-left: 30em;margin-bottom: 3em;">
			<%= link_to 'Show Student Details'.html_safe, @student, class: 'btn btn-outline-info rounded' %> <br> 
			<% link_to 'Back <i class="bi bi-arrow-left-circle"></i>'.html_safe, students_path, class: 'btn btn-outline-dark' %>
	</div>
	<% end %>
</div>

app/views/students/index.html.erb
<!--<h3 style="margin-bottom:20px;">Students</h3> -->

<div class="container text-center" style="margin-bottom:0.6em;">
  <div class="container mb-3">
    <%= render 'students/search_form.html.erb' %>
    <%= link_to 'Add New Student', new_student_path, class:'btn btn-outline-primary rounded mx-auto mt-3'  %>
    <% if current_user.admin? %>
        <button type="button" class="btn rounded btn-outline-primary mx-auto mt-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Import Students
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" style="font-family: open-sans;">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header bg-primary">
                <h5 class="modal-title" id="exampleModalLabel">Import Students via CSV File</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <%= form_tag import_students_path, multipart: true do %>
                  <span class="btn btn-sm btn-secondary btn-file" style="margin-bottom:1em;">
                  <%= file_field_tag :file, accept: '.csv', style: 'width:300px;', class: 'fw-bolder' %></span>
                  <%= submit_tag "Upload File!",class: 'btn btn-outline-success btn-round btn-sm', style: 'width:15em;' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    <!--<button class="btn btn-outline-primary dropdown-toggle rounded" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" style="margin-left: 5em;">
      More Options
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <%# if current_user.admin? %>
        <li><%# link_to 'TC Student List', removed_students_path , class:'dropdown-item' %></li>
      <%# end %>
      <li><%# link_to 'Add New Student', new_student_path, class:'dropdown-item' %></li>
    </ul> -->
  </div>
</div>

<div class="table-responsive">
  <table class="table table-sty table-hover table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Date of Birth</th>
        <th>Date of Admission</th>
        <th>Admission no</th>
        <th>Phone number</th>
        <th>Email</th>
        <th>Class</th>
        <th>Section</th>
        <th>Father name</th>
        <th>Mother name</th>
        <th class="text-center" colspan="4">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.first_name %></td>
          <td><%= student.last_name %></td>
          <td><%= student.dob.strftime("%d-%m-%Y") unless !student.dob.present?%></td>
          <td><%= student.date_of_admission.strftime("%d-%m-%Y") unless !student.date_of_admission.present?%></td>
          <td><%= student.admission_no %></td>
          <td><%= student.phone_number %></td>
          <td><%= student.email %></td>
          <td><%= student.grade %></td>
          <td><%= student.section %></td>
          <td><%= student.father_name %></td>
          <td><%= student.mother_name %></td>
          <td><button type="button" class="btn btn-tip" data-bs-toggle="tooltip" trigger="hover focus" title="Show Student invoices">
                  <%= link_to '<i class="bi bi-receipt-cutoff"></i>'.html_safe, students_show_invoices_path(student), class: 'btn btn-info btn-sm' %></button></td>
          <td><button type="button" class="btn btn-tip" data-bs-toggle="tooltip" title="Edit Student Data">
            <%= link_to '<i class="bi bi-pass-fill"></i>'.html_safe, edit_student_path(student), class: 'btn btn-secondary btn-round btn-sm' %></button></td>
          <td><button type="button" class="btn btn-tip" data-bs-toggle="tooltip" title="Delete">
            <%= link_to '<i class="bi bi-trash3-fill"></i>'.html_safe, student, method: :delete, class: 'btn btn-danger btn-round btn-sm', data: { confirm: 'Are you sure?' } %></button></td>
          <td><%= link_to 'Add <i class="bi bi-receipt-cutoff"></i>'.html_safe, new_student_invoice_path(student), class: 'btn btn-primary btn-round btn-sm' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="text-center" style="margin-bottom: 2.5em;">
  <%= paginate @students %>  
  
        <%# if current_user.admin? %>
             <!-- <div class="card" id="import-crd">
                <div class="card-header">
                  <h5>Import Students From CSV File</h5>
                </div>
                <div class="card-body" style="background-color:#333;">
                  <div class="input-group" id="import-grp">
                
                      <%# form_tag import_students_path, multipart: true do %>
                        <span class="btn btn-sm btn-info btn-file opacity-50" style="margin-bottom:1em;">
                        <%# file_field_tag :file, accept: '.csv', style: 'width:300px;', class: 'fw-bolder' %></span>
                        <%# submit_tag "Upload File!",class: 'btn btn-outline-success btn-round btn-sm', style: 'width:15em;' %>
                      <%# end %>

                    
                  </div>
                </div>
              </div> -->
        <%# end %>
</div>

app/views/students/new.html.erb
<div class="container text-center" style="max-width:60em;font-family: 'open-sans';">
	<h2>Create a new Student</h2>

	<%= render 'form', student: @student %>
	<%# link_to 'Back <i class="bi bi-arrow-left-circle"></i>'.html_safe, students_path, class: 'btn btn-outline-dark', style: 'margin-left:40em; margin-top:1em;' %>
	
</div>

app/views/students/pending_data.html.erb
<div class="card border-dark" style="font-family: open-sans; font-size: 0.9em;">
		<div class="card-header text-dark">
			<div class="table-responsive">
				<table class="table table-hover table-bordered">
					<thead>
						<tr>
							<th>First name</th>
							<th>Last name</th>
							<th>Date of Birth</th>
							<th>Date of Admission</th>
							<th>Admission no</th>
							<th>Phone number</th>
							<th>Class</th>
							<th>Section</th>
							<th>Father name</th>
							<th>Mother name</th>
							<th colspan="3"></th>
						</tr>
					</thead>


					<tbody>
						<% @students.each do |student| %>
							<tr>
										<td><%= student.first_name %></td>
								        <td><%= student.last_name unless !student.last_name.present? %></td>
								        <td><%= student.dob.strftime("%d-%m-%Y") unless !student.dob.present? %></td>
								        <td><%= student.date_of_admission.strftime("%d-%m-%Y") unless !student.date_of_admission.present? %></td>
								        <td><%= student.admission_no unless !student.admission_no.present?%></td>
								        <td><%= student.phone_number unless !student.phone_number.present? %></td>
								        <td><%= student.grade %></td>
								        <td><%= student.section %></td>
								        <td><%= student.father_name unless !student.father_name.present? %></td>
								        <td><%= student.mother_name unless !student.mother_name.present? %></td>
								        <td><%= link_to 'Edit', edit_student_path(student), class: 'btn btn-secondary btn-round btn-sm' %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>			
		</div>
</div>

app/views/students/pending_fee.html.erb
<div class="container text-center" style="font-family: open-sans; max-width: 75em;font-size: 0.9em;">
	<div class="card border-dark">
		<div class="card-header text-dark">
			<p class="fw-bolder">Students Pending Fee List</p>
		</div>

		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-hover table-sm">
					<thead>
						<tr>
							<th>ID</th>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Class</th>						
							<th>Actions</th>
						</tr>
					</thead>

					<tbody>
						<% @students.order(grade: :desc).each do |student| %>
						<tr>
							<td><%= student.id %></td>
							<td><%= student.first_name %></td>
							<td><%= student.last_name %></td>
							<td><%= student.grade %></td>
							<td>
								<div class="btn-group justify-content-around">
									<button class="btn btn-sm btn-outline-primary me-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample<%= student.id %>" aria-expanded="false" aria-controls="collapseExample">
										<i class="bi bi-exclamation-triangle-fill"></i>
									</button>
									<div class="collapse" id="collapseExample<%= student.id %>">
										<div class="card card-body bordered">
											<% if student.pending_fees.keys.count > 1 %>
												<% student.pending_fees.keys.each do|year| %>
													<div class="vstack gap-1 mx-auto">
														<button class="btn btn-outline-secondary text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample<%= student.id.to_s+year %>" aria-expanded="false" aria-controls="collapseExample">	   
															Year: <%= year %>
														</button>								      						        
														<div class="collapse" id="collapseExample<%= student.id.to_s+year %>">	
															<div class="card card-body border-danger">
																<% if year.to_i != Time.zone.today.year %>
																	<% month_names(student.pending_fees[year]).each do |months| %>
																			<span class="fw-bolder"><%= month_names(student.pending_fees[year]).count > 1 && months != "December" ? months+"," : months %></span>
																	<% end %>
																<% else %>
																	<% month_names(student.pending_fees[year]).each do |months| %>
																		<% if months.to_date < Time.zone.today %>
																			<span class="fw-bolder"><%= month_names(student.pending_fees[year]).count > 1 && months != "December" ? months+"," : months %></span>
																		<% end %>
																	<% end %>
																<% end %>
															</div>
														</div>
												</div> 
												<% end %>
											<% else %>
											<div class="vstack gap-1 mx-auto">    
											<button class="btn btn-outline-secondary text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample<%= student.id.to_s+student.grade %>" aria-expanded="false" aria-controls="collapseExample">
													Year: <%= student.pending_fees.keys.first %>
												</button>
												<div class="collapse" id="collapseExample<%= student.id.to_s+student.grade %>">
													<div class="card card-body border-danger">
															<% month_names(student.pending_fees.values.first).each do |months| %>
																<span class="fw-bolder"><%= month_names(student.pending_fees.values.first).count > 1 && months != "December" ? months+"," : months %><span></span>
														<% end %>
													</div>
												</div>
											</div>								        
											<% end %>
										</div>
									</div>																							
									<%= link_to '<i class="bi bi-receipt-cutoff"></i>'.html_safe, students_show_invoices_path(student), class: 'btn btn-outline-primary btn-sm me-2' %>											
									<%= button_to({ action: "send_fee_reminder", id: student.id },
													method: :post,
													data: { confirm: "Sending message of fee reminder to the student. Press Ok to confirm and send.",
															disable_with: "Sending........" },
													class: "btn btn-outline-primary btn-sm me-2") do %>
										<i class="bi bi-send-check-fill"></i>
									<% end %>
								</div>
							</td>						
						</tr>
						<% end %>		
					</tbody>
					
				</table>
			</div>
		</div>

		<div class="card-footer">
			<%= paginate @students %>
		</div>
	</div>
</div>

app/views/students/show.html.erb
<div class="container text-center" style="max-width:40em;">
    <div class="card border-dark ">
        <div class="card-header text-dark" style="font-family: open-sans;">
            <p>
              <strong>First name:</strong>
              <%= @student.first_name %>
            </p>

            <p>
              <strong>Last name:</strong>
              <%= @student.last_name %>
            </p>

            <p>
              <strong>Date of Birth:</strong>
              <%= @student.dob %>
            </p>

            <p>
              <strong>Date of Admission:</strong>
              <%= @student.date_of_admission %>
            </p>

            <p>
              <strong>Admission no:</strong>
              <%= @student.admission_no %>
            </p>

            <p>
              <strong>Phone number:</strong>
              <%= @student.phone_number %>
            </p>

            <p>
              <strong>Grade:</strong>
              <%= @student.grade %>
            </p>

            <p>
              <strong>Section:</strong>
              <%= @student.section %>
            </p>

            <p>
              <strong>Father name:</strong>
              <%= @student.father_name %>
            </p>

            <p>
              <strong>Mother name:</strong>
              <%= @student.mother_name %>
            </p>

            <div class="card-footer text-center">
                <div class="btn-group">
                    <%= link_to 'Edit <i class="bi bi-pass-fill"></i>'.html_safe, edit_student_path(@student), class: 'btn btn-outline-secondary' %>
                    <!--<% link_to 'Back <i class="bi bi-arrow-left-circle"></i>'.html_safe, students_path, class: 'btn btn-outline-dark' %> -->
                    <%= link_to 'Show <i class="bi bi-receipt-cutoff"></i>'.html_safe, students_show_invoices_path(@student), class: 'btn btn-outline-dark' %>
                    <%= link_to 'Add <i class="bi bi-receipt-cutoff"></i>'.html_safe, new_student_invoice_path(@student), class: 'btn btn-outline-dark' %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/students/student_invoices.html.erb
<div class="container" style="max-width: 75em;font-family: open-sans;font-size: 0.98em;">
	<div class="card border-dark align-self-center text-center" id="show-invoices-for-stu">
		<div class="card-header text-dark">
			<div class="card-title">
			<ul class="list-inline text-center d-flex justify-content-center">
				<li class="inv-list">Invoices for Student: <%= link_to @student.first_name, student_path(@student) %></li>
				<li class="inv-list">Class: <%= @student.grade unless !@student.grade.present? %></li>
			</ul>
			</div>
		</div>

		<div class="card-body text-center">
			<table class="table invoice-sty table-hover table-sm">
			            <thead>
			              <tr>
			              	  <th>Invoice ID</th>
			                  <th>Date</th>
			                  <th>Student</th>
			                  <th>Total</th>
			                  <th>Payment Mode</th>
			                  <th>Paid for</th>
			                  <% if current_user.admin? %>
			                  	<th>Submitted By</th>
			                  	<th>Deleted?</th>
			                  <% end %>
			                  <th>Invoice Notes</th>
			                </tr>
			            </thead>

		
					<tbody>
			                	<% @invoices.order(created_at: :desc).each do |invoice| %>
			                      <tr>
			                      	<td><%= link_to invoice.id, invoice_path(invoice) %></td>
			                        <td><%= invoice.created_at.strftime("%d-%m-%Y") %></td>
			                        <td><%= invoice.student.first_name %></td>
			                        <td><%= invoice.total %></td>
			                        <td><%= invoice.payment_mode %></td>
			                        <td>
			                          <% if month_name(invoice.month_from) != month_name(invoice.month_to) %>
			                              <%= month_name(invoice.month_from).present? ? month_name(invoice.month_from)+" "+invoice.month_to.split("-").first[2,3] : "<a href='#''>Missing</a>".html_safe %> to <%= month_name(invoice.month_to).present? ? month_name(invoice.month_to)+" "+invoice.month_to.split("-").first[2,3] : "<a href='#''>Missing</a>".html_safe %>
			                            <% else %>
			                              <%= month_name(invoice.month_to).present? ? month_name(invoice.month_to)+" "+invoice.month_to.split("-").first[2,3] : "<a href='#''>Missing</a>".html_safe %>
			                            <% end %>
			                        </td>
			                        
			                        <% if current_user.admin? %>
			                        	<td><%= invoice.user.username %></td>

			                      	<td>
			                      		<% if current_user.admin? && invoice.discarded? %>
			                      			<p style="font-size: inherit;">Deleted by <%= User.find_by_id(invoice.discarded_by).username unless !invoice.discarded_by.present? %></p>
			                      		<% else %>
			                      			<p style="font-size: inherit;">No</p>
			                      		<% end %>
			                      		
			                      	</td>
			                      	<% end %>

			                      	<td>
			                      		<% if invoice.notes.present? %>
			                      		    <%= invoice.notes %>
			                      		<% end %>                  
			                      	</td>

			                      </tr>
			                    <% end %>
			        </tbody>

			        <tfoot>
			        		<!--<th colspan="3"></th>
			        		<th>Total amount Paid: <% @invoices.sum(:total) %></th> -->
			        </tfoot>
			</table>
		</div>
		<div class="card-footer">
			<% link_to 'Back <i class="bi bi-arrow-left-circle"></i>'.html_safe, students_path, class: 'btn btn-outline-dark' %>
			<span class="fw-bolder">Total amount Paid: <%= @invoices.kept.sum(:total) %></span>
		</div>
	</div>
</div>