config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  get 'fee_reminder/index'
  post 'fee_reminder/index'
  get 'send', to: 'fee_reminder#send_message'
  post 'send', to: 'fee_reminder#send_message'
  
  resources :students do
    collection { post :import}
    
    collection do
      get 'pending_fee'
      post 'pending_fee', to: 'students#send_fee_reminder', as: 'send_fee_reminder_path'
      get 'missing'
      get 'removed'
    end

    member do
      patch :undiscard      
    end
    resources :invoices
  end
 
  

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  #/student/:id/update_

  
  get 'invoices/print/:id', to: 'invoices#print', as: 'invoices_print'


  #get 'invoices#cheque', to: 'invoices#cheque', as: 'invoice_cheque'

  #get 'students#missing', to: 'students#missing', as: 'students_missing'


  get 'invoices/show/:id', to: 'students#show_invoices', as: 'students_show_invoices'

  resources :invoices do
      collection do
        match 'search' => 'invoices#search', via: [:get, :post], as: :search

        get 'cheque'

      end

      resources :particulars, except: [:show], controller: 'invoices/particulars'
  end

  namespace :admin do
    resources :dashboard
  end

  root 'invoices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #6269a1;">
    <!--<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span></button> -->

<div class="navbar-collapse" id="navbarTogglerDemo01">
  <a class="navbar-brand" ><% image_tag 'logo.jpg' %></a>
  
  <!--<a class="user-txt text-dark">
    <%# if current_user %>    
            <%# if current_user.admin? %>
              <h4>Hi! <%# current_user.username.capitalize %> (Admin)</h4>
            <%# else %>
              <h4>Hi! <%# current_user.username.capitalize %> </h4>
            <%# end %>
    <%# end %></a> -->
            <!-- <div class="salution-header">
                <%# if Time.zone.now < Time.zone.now.middle_of_day %>
                    <h4 class="usr-salut-head">Good Morning! <%# current_user.username %> (Admin)</h4>
                <%# elsif Time.zone.now > Time.zone.now.middle_of_day && Time.zone.now < (Time.zone.now.middle_of_day+4.hours) %>
                    <h4 class="usr-salut-head">Good Afternoon! <%# current_user.username %> (Admin)</h4>
                <%# else %>
                    <h4 class="usr-salut-head">Hi! <%# current_user.username %> (Admin)</h4>
                <%# end %>
            </div>
          
            
            <%# if Time.zone.now < Time.zone.now.middle_of_day %>
                <h4 class="usr-salut-head">Good Morning! <%# current_user.username %></h4>
            <%# elsif Time.zone.now > Time.zone.now.middle_of_day && Time.zone.now < (Time.zone.now.middle_of_day+4.hours) %>
                <h4 class="usr-salut-head">Good Afternoon! <%# current_user.username %></h4>
            <%# else %>
                <h4 class="usr-salut-head">Good Evening! <%# current_user.username %></h4> 
            <%# end %> -->
  <%# if current_user %>
     <!-- <div class="d-grid col-6 mx-auto">
                      <ul class="navbar-nav nav-fill justify-content-right">
                            <li class="nav-item">
                              <a><%# link_to "Home", root_path, class: 'nav-link active fw-bolder'%></a>
                            </li>
                            <li class="nav-item">
                              <a><%# link_to "Students", students_path, class: 'nav-link active fw-bolder'%></a>
                            </li>                                  
                      </ul>
      </div> -->
  <%# else %>
      <!-- <div class="d-grid col-6 mx-auto text-center">
          <h4 class="nav-header-txt">BillTraq</h4>
      </div> -->

    <div class="d-grid col-6 mx-auto text-center">
      <div class="waterfall-text">
        <span class="letter">B</span>
        <span class="letter">i</span>
        <span class="letter">l</span>
        <span class="letter">l</span>
        <span class="letter">T</span>
        <span class="letter">r</span>
        <span class="letter">a</span>
        <span class="letter">q</span>        
      </div>
    </div>
  <%# end %>

  <div class="d-grid ml-auto">

    <%# if current_user %>
       <!-- <div class="btn-group">          

          <div class="dropdown" style="margin-right: 1.5em;">                          
                  <button class="btn btn-outline-info dropdown-toggle rounded" type="button" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Menu
                  </button>
                  <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">                   
                        <a><%# link_to 'Pending Fee List', pending_fee_students_path, class:'dropdown-item' %></a>
                        <a><%# link_to "Missing Data", missing_students_path, class: 'dropdown-item'%></a>
                  </div>
          </div>

          <div class="dropdown">
            <button class="btn btn-outline-info dropdown-toggle rounded" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true">              
                <%# current_user.username.titleize %>              
            </button>
              <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end text-center" aria-labelledby="dropdownMenuButton1">
                <li><%# button_to "Log Out", destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
              </ul>
          </div>                    
      </div>
    <%# end %> -->
   
    <div class="btn-group mt-2">
      <% link_to "Sign Up", new_user_registration_path, class: 'btn btn-outline-info rounded me-2'%>
      <% link_to "Log In", new_user_session_path, class: 'btn btn-outline-info rounded' %>
    </div>    
  </div>  
  
</div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <%= image_tag 'logo.jpg', style:'height:50%;width:70%' %>
            <strong>YL</strong>
        </div>
        <ul class="list-unstyled components">
            <li class="active">
                <!-- <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-home"></i>
                    Home
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <a href="#">Home 1</a>
                    </li>
                    <li>
                        <a href="#">Home 2</a>
                    </li>
                    <li>
                        <a href="#">Home 3</a>
                    </li>
                    </ul> -->
                <%= link_to "<i class='fas fa-home'></i> Home".html_safe, root_path %>
            </li>
            <li>
                <!-- <a href="#">
                    <i class="fas fa-briefcase"></i>
                    About
                    </a>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-copy"></i>
                    Pages
                    </a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#">Page 1</a>
                    </li>
                    <li>
                        <a href="#">Page 2</a>
                    </li>
                    <li>
                        <a href="#">Page 3</a>
                    </li>
                    </ul> -->
                <%= link_to "<i class='fas fa-user-graduate	'></i> Students".html_safe, students_path %>
            </li>
            <li>
                <%= link_to "<i class='fas fa-calendar-times'></i> Pending Fee List".html_safe, pending_fee_students_path %>
            </li>
            <li>
                <%= link_to "<i class='fas fa-user-times'></i>  Missing Data".html_safe, missing_students_path %>
            </li>
            <% if current_user.admin? %>
            <li>
                <%= link_to "<i class='fas fa-list-ul'></i> TC Student List".html_safe, removed_students_path %>
            </li>
            <li>
                <%= link_to "<i class='fas fa-money-check'></i> Cheque Data".html_safe, cheque_invoices_path %>
            </li>
            <li>                    
                <%= link_to "<i class='fas fa-chart-bar'></i> Dashboard".html_safe, admin_dashboard_index_path %>
            </li>
            <li>
                <%= link_to "<i class='fas fa-paper-plane'></i> Communication".html_safe, fee_reminder_index_path %>
            </li>
            <% end %>                
        </ul>
        <ul class="list-unstyled CTAs">
            <!--<li>                                        
                <a href="#" class="article">Logged in as <%= current_user.username %></a>
                </li>-->
            <li>
                <p class="article">Logged in as <u><%= current_user.username %></u></p>
            </li>
            <li>
                <p class="article">Last Log in: <%= current_user.current_sign_in_at.present? ? time_ago_in_words(current_user.current_sign_in_at) +' ' + 'ago' : 'Never Logged In' %></p>
            </li>
            <li>
                <!-- <a href="#" class="article">Somthing</a>
                <%= link_to "Log Out", destroy_user_session_path, class: 'download text-center', method: :delete %> -->
            </li>
        </ul>
    </nav>
    <div id="content">
        <div>
            <%= render "layouts/sidebar_nav" %>
        </div>
        <div class="container mb-2">
            <% if flash[:notice] %>
            <div class="alert alert-success alert-dismissible fade show m-1 text-center" role="alert" style="height:55px;">
                <p class="text-center fw-bolder" style="font-size:18px;"><%= flash[:notice] %></p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"></span>
                </button>
            </div>
            <% elsif flash[:error] %>
            <div class="alert alert-danger alert-dismissible fade show m-1" role="alert" style="height:55px;">
                <p class="text-center fw-bolder" style="font-size:18px;"><%= flash[:error] %></p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"></span>
                </button>
            </div>
            <% elsif flash[:alert] %>
            <div class="alert alert-primary alert-dismissible fade show m-1" role="alert" style="height:55px;">
                <p class="text-center fw-bolder" style="font-size:18px;"><%= flash[:alert] %></p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"></span>
                </button>
            </div>
            <% end %>                    
        </div>
        <div class="container-fluid">
            <button type="button" id="sidebarCollapse" class="btn btn-info mb-2 sidebar-tog">
            <i class="fas fa-align-left"></i>
            <span>Toggle Sidebar</span>
            </button>
            <%= yield %> 
        </div>
    </div>
</div>

app/views/layouts/_sidebar_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #6269a1;">
    <!--<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span></button> -->

    <div class="navbar-collapse" id="navbarTogglerDemo01">              
        <% if current_user %>
            <div class="d-grid col-6 mx-auto">
                <ul class="navbar-nav nav-fill justify-content-right">
                    <li class="nav-item">
                        <a><%= link_to "Home", root_path, class: 'nav-link active fw-bolder'%></a>
                    </li>
                    <li class="nav-item">
                        <a><%= link_to "Students", students_path, class: 'nav-link active fw-bolder'%></a>
                    </li>                
                </ul>            
            </div>
            <div class="dropdown">
                <a class="nav-link dropdown-toggle" id="avatarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="avatar-circle">                                                    
                        <%= image_tag 'avatar.jpeg', alt: "Avatar", class: "avatar-img" %>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="avatarDropdown">
                    <li><p class="dropdown-item-disabled" style="padding-left: 16px;">Hi <%= current_user.username %>!</p></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Log Out", destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                </div>
            </div>  
        <% end %>    
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Billtraq</title>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    
    
    <!-- Some issue while creating the app led to issues with bootstrap js to install in app -->
    <!-- Hence including those via CDN to have nav tabs and other js dependant functionality working -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

  </head>

  <body>
    <!-- Both admin and non admin users now go to sidebar. -->
    <% if current_user %>
      <%= render "layouts/sidebar" %>
    <% else %>    
      <%= render "layouts/navbar" %>
      <div class="container-fluid">
            <!-- Blocked header to render before login works for both html & css code-->
          <div>
            <% if flash[:notice] %>
              <div class="alert alert-success alert-dismissible fade show m-1 text-center" role="alert" style="height:55px;">
                <p class="text-center fw-bolder" style="font-size:18px;"><%= flash[:notice] %></p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true"></span>
                    </button>
              </div>
            <% elsif flash[:error] %>
              <div class="alert alert-danger alert-dismissible fade show m-1" role="alert" style="height:55px;">
                <p class="text-center fw-bolder" style="font-size:18px;"><%= flash[:error] %></p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true"></span>
                    </button>
              </div>
              <% elsif flash[:alert] %>
              <div class="alert alert-primary alert-dismissible fade show m-1" role="alert" style="height:55px;">
                <p class="text-center fw-bolder" style="font-size:18px;"><%= flash[:alert] %></p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true"></span>
                    </button>
              </div>
            <% end %>
          </div>
          <%= yield %>          
      </div>
    <% end %>
    <footer class="footer">
      <div class="container text-center">
        <span class="text-muted">Powered by &#169; <a href="https://www.rorsolutions.in" target="_blank">RoRSolutions</a></span>
      </div>
    </footer>
    </body>
</html>